# Start process so that the data is new
https://triple-func.azurewebsites.net/api/StartProcess

# Get any city using the city query parameter (Venlo as example)
https://triple-func.azurewebsites.net/api/AccessImages?city=Venlo